services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ${USERPROFILE}/Documentos/Docker/teste/PostgreSQL/teste:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080

  jsp-app:
    build: 
      context: .
#    volumes:
#      - ./target:/usr/local/tomcat/webapps/
    depends_on:
      - postgres
    ports:
      - 8080:8080